---
- name: sysctl kernel.pid_max
  sysctl: name=kernel.pid_max value=4194303 sysctl_set=yes state=present reload=yes

- name: sysctl vm.swappiness 
  sysctl: name=vm.swappiness value=1 sysctl_set=yes state=present reload=yes

- name: sysctl vm.swappiness 
  sysctl: name=vm.vfs_cache_pressure value=1 sysctl_set=yes state=present reload=yes

- name: make sure that bond0 has the xmit_hash_policy=layer2+3
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-bond0 regexp=^BONDING_OPTS line='BONDING_OPTS="miimon=100 mode=4 xmit_hash_policy=layer2+3"'

- name: sysctl net.ipv4.tcp_timestamps=0
  sysctl: name=net.ipv4.tcp_timestamps value=0 sysctl_set=yes state=present reload=yes

- name: sysctl net.core.netdev_max_backlog
  sysctl: name=net.core.netdev_max_backlog value=250000 sysctl_set=yes state=present reload=yes

- name: sysctl net.core.rmem_max
  sysctl: name=net.core.rmem_max value=16777216 sysctl_set=yes state=present reload=yes

- name: sysctl net.core.wmem_max
  sysctl: name=net.core.wmem_max value=16777216 sysctl_set=yes state=present reload=yes

- name: sysctl net.core.rmem_default
  sysctl: name=net.core.rmem_default value=16777216 sysctl_set=yes state=present reload=yes

- name: sysctl net.core.wmem_default
  sysctl: name=net.core.wmem_default value=16777216 sysctl_set=yes state=present reload=yes

- name: sysctl net.core.optmem_max
  sysctl: name=net.core.optmem_max value=16777216 sysctl_set=yes state=present reload=yes

- name: sysctl net.ipv4.tcp_low_latency
  sysctl: name=net.ipv4.tcp_low_latency value=1 sysctl_set=yes state=present reload=yes

- name: sysctl net.ipv4.tcp_rmem
  sysctl: name=net.ipv4.tcp_rmem value="4096 87380 16777216" sysctl_set=yes state=present reload=yes

- name: sysctl core.netdev_budget 
  sysctl: name=net.core.netdev_budget value=600 sysctl_set=yes state=present reload=yes
