---
- name: save the config
  uri: 
    url: 'http://192.168.241.3/admin/launch?script=rh&template=login&action=login'
    method: POST
    body: "f_user_id=xmladmin&f_password=xmladmin"
    status_code: 302
    HEADER_Content-Type: "application/x-www-form-urlencoded"
  register: login

- name: get some info
  uri:
    url: 'http://192.168.241.3/xtree'
    method: POST
    body: "{{ lookup('file','getChMo.xml') }}"
    #body: file:///root/getChMo.xml
    #body_format: raw
    #body: '<?xml version="1.0" encoding="UTF-8" standalone="no"?>
#<xg-request>
# <action-request>
# <action-name>/do_rest</action-name>
# <nodes>
# <node>
# <name>get</name>
# <type>string</type>
# <value>/mlnxos/v1/chassis/model</value>
# </node>
# </nodes>
# </action-request>
#</xg-request>
#'
    HEADER_Cookie: "{{login.set_cookie}}"
    HEADER_Content-Type: "application/x-www-form-urlencoded"
    return_content: yes
    dest: /backup/output
