---
- name: ceph deploy head install cephpkgs
  hosts: cephdep
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephcbthead

- name: ceph base install MONS
  hosts: mons
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephmons

- name: ceph base install OSDS
  hosts: osds
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephosds

- name: ceph base install RGWS
  hosts: rgws
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephrgws

- name: ceph base install MDSS
  hosts: mdss
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephmdss

- name: cbt head install cephpkgs
  hosts: cbthead
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephcbthead

- name: cbt client install cephpkgs
  hosts: cbtclients
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephcbtclients

- name: ceph deploy head install cephpkgs
  hosts: cephdep
  roles:
    - ../roles/repos
    - ../roles/cephdep
    - ../roles/cephcbthead
